### ISSUE TITLE
Release fix

### ISSUE THREAD

**Issue by amihaiemil** [opencharles/mention-notifications-ejb#10]
The ejb checker class is final and cannot be instantiated at least by Glassfish's ejb container.
Fix this and release it.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
seems to work fine

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@rultor release, tag is `1.1.0`

**Comment by amihaiemil** [comment]
Done; version ``1.1.0`` seems to work fine
