### ISSUE TITLE
HTTPS PKIX validation problem

### ISSUE THREAD

**Issue by amihaiemil** [opencharles/mention-notifications-ejb#17]
[2017-09-24T20:14:38.433+0000] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=218 _ThreadName=Thread-8] [timeMillis: 1506284078433] [levelValue: 800] [[

  2017-09-24 20:14:38 ERROR GithubNotificationsCheck:125 - IOException when checking or sending notifications: 

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)

**Comment by amihaiemil** [comment]
Add ``TrustyRequest`` decorator, so the HTTP request is done through ``TrustedWire``: http://http.jcabi.com/pkix-validator.html

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1.2`

**Comment by amihaiemil** [comment]
@rultor release again, tag is `1.1.3`

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@rultor release again, tag is `1.1.4`

**Comment by amihaiemil** [comment]
@charlesmike hello, does the released ejb work?

**Comment by charlesmike** [comment]
> @charlesmike hello, does the released ejb work?

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
the checker now works, closing this...
